```{r}
#Naufal Rasyid Sutansyah2 Telco Churn Dataset

#load library
library(readr)
library(psych)
library(ggplot2)
library(DataExplorer)
library(randomForest)
library(tidyverse)
```

```{r}
setwd('C:/Users/LENOVO THINKPAD T460/Downloads/Telco_Customer')
getwd()

data<- read_csv("C:/Users/LENOVO THINKPAD T460/Downloads/Telco_Customer/TelcoCustomerChurn.csv")
```
```{r}
#checking top dataset
head(data)
#checking dataset
str(data)
#checking missing values
sum(is.na(data))
#checking dulicated data
sum(duplicated(data))
summary(is.na(data))
#summary statistic
summary(data)
```
```{r}
library(naniar)
library(scales)
# Visualize missing values in data_Covid19 by variables
missingvalues <- gg_miss_var(data) +
  scale_y_continuous(labels = scales::number_format(scale = 1, accuracy = 1, big.mark = ",", decimal.mark = "."))
#print result
(missingvalues)
```
```{r}
data %>% filter(is.na(TotalCharges)) %>% select(TotalCharges, Churn, tenure, MonthlyCharges)
#Drop NA rows in total charges
data_clean <- data[!is.na(data$TotalCharges),]

# Visualize missing values in dataset by variables
missingvalues <- gg_miss_var(data_clean) +
  scale_y_continuous(labels = scales::number_format(scale = 1, accuracy = 1, big.mark = ",", decimal.mark = "."))
#print result
(missingvalues)

```

```{r}
plot(data_clean)
```

```{r}
#Check outliers
plot_intro(data_clean)
```
```{r}
#Corelation and distribution check
data_clean %>% 
  select(tenure, MonthlyCharges, TotalCharges, Churn) %>%
  ggpairs(aes(color = fct_rev(Churn)), title = "Customer Account Distributions and Correlations \n",
          columnLabels = c("Tenure", "Monthly Charges", "Total Charges", "Churn"),
          upper = list(combo = wrap("box_no_facet", alpha = 0.7)),
          diag = list(continuous = wrap("densityDiag", alpha = 0.6), 
                      discrete = wrap("barDiag", alpha = 0.7, color = "grey30")),
          lower = list(combo = wrap("box_no_facet", alpha = 0.7), continuous = wrap("smooth", alpha = 0.15)))
```
```{r}
#corelation checkr for numercial variable
numeric.var <- sapply(data_clean, is.numeric) ## Find numerical variables
corr.matrix <- cor(data_clean[,numeric.var])  ## Calculate the correlation matrix
corrplot(corr.matrix, main="\n\nCorrelation Plot for Numeric Variables", method="number")
```


```{r}
prop.table(table(data_clean$Dependents,data_clean$Churn),1)
prop.table(table(data_clean$OnlineSecurity,data_clean$Churn),1)
prop.table(table(data$InternetService,data$Churn),1)
```
```{r}
#Check customer Gender
ggplot(data = data_clean, aes(x = gender)) +
  geom_bar(aes(fill = gender)) + 
  geom_text(stat = 'count', aes(label = stat(count)), vjust = -0.25) +
  labs(title = "Analysis Customer Gender",
       x = "Gender",
       y = "Count")+
  scale_fill_manual(values = c("#E69F00", "#56B4E9")) +
  theme_minimal()
```

```{r}
table(data_clean$PaymentMethod)
#Payment Method paling sering dipakai
ggplot(data = data_clean, aes(x = PaymentMethod)) +
  geom_bar(aes(fill = PaymentMethod)) + 
  geom_text(stat = 'count', aes(label = stat(count)), vjust = -0.25, 
            position = position_stack(vjust = 0.5), color = "white", size = 4) +
  labs(title = "Analysis of Payment Methods",
       subtitle = "Which Payment Methods are Most Frequently Used?",
       x = "Payment Method",
       y = "Count") +
  scale_fill_manual(values = c("#E69F00", "#56B4E9", "#D55E00", "#6E614D")) +
  theme_minimal() + 
  coord_flip()

```

```{r}
table(data_clean$gender, data_clean$PaymentMethod)

#payment based on gender
ggplot(data = data_clean, aes(x = PaymentMethod, fill = gender)) +
  geom_bar(position = "dodge") + 
  labs(title = "Analisis Payment by Gender",
       subtitle = "Payment with Gender Distribution",
       x = "Payment",
       y = "Count")  +
  scale_fill_manual(values = c("#E69F00", "#56B4E9")) +
  theme_minimal()
```
```{r}
#Check customer Partner
ggplot(data = data_clean, aes(x = Partner)) + 
  geom_bar(aes(fill = Partner)) + 
  geom_text(stat = 'count', aes(label = stat(count)), vjust = -0.25) +
  labs(title = "Analysis Customer Patner",
       x = "Partner",
       y = "Count")+
  scale_fill_manual(values = c("#D55E00", "#56BB70")) +
  theme_minimal()
```
```{r}
#Check customer Dependants
ggplot(data = data_clean, aes(x = Dependents)) + 
  geom_bar(aes(fill = Dependents)) + 
  geom_text(stat = 'count', aes(label = stat(count)), vjust = -0.25) +
  labs(title = "Analysis Customer Dependents",
       x = "Dependants",
       y = "Count")+
  scale_fill_manual(values = c("#D55E00", "#56BB70")) +
  theme_minimal()
```

```{r}
table(data_clean$gender, data_clean$Churn)

# Calculate gender by churn
gender_churn <- data_clean %>%
  group_by(Churn, gender) %>%
  summarize(Count = n())

# Plotting
ggplot(data = gender_churn, aes(x = Churn, y = Count, fill = gender)) +
  geom_bar(position = "dodge", stat = "identity") +
  geom_text(aes(label = Count), position = position_dodge(width = 0.9), vjust = -0.5, color = "black") +
  labs(title = "Analysis of Churn by Gender",
       x = "Churn",
       y = "Count") +
  scale_fill_manual(values = c("#E69F00", "#56B4E9")) +
  theme_minimal()


```
```{r}
#Check customer phone service
ggplot(data = data_clean, aes(x = PhoneService)) + 
  geom_bar(aes(fill = PhoneService)) + 
  geom_text(stat = 'count', aes(label = stat(count)), vjust = -0.25) +
  labs(title = "Analysis Customer PhoneService",
       x = "Phone Service",
       y = "Count")+
  scale_fill_manual(values = c("#D55E00", "#56BB70")) +
  theme_minimal()

```
```{r}
#Check customer contract
ggplot(data = data_clean, aes(x = Contract)) + 
  geom_bar(aes(fill = Contract)) + 
  geom_text(stat = 'count', aes(label = stat(count)), vjust = -0.25) +
  labs(title = "Analysis Customer Contract",
       x = "Contract",
       y = "Count")+
  theme_minimal()

# Calculate count for each contract
contract <- data_clean %>%
  group_by(Contract) %>%
  summarize(Count = n()) %>%
  arrange(desc(Count))

# Plotting
ggplot(data = contract, aes(x = reorder(Contract, -Count), y = Count)) +
  geom_bar(aes(fill = Contract), stat = "identity") +
  geom_text(aes(label = Count), vjust = -0.25) +
  labs(title = "Analysis of Customer Contracts",
       x = "Contract",
       y = "Count") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))


```


```{r}
#MODELING USING RANDOM FOREST
# Manually split the data into train and test datasets
set.seed(42)
train_indices <- sample(1:nrow(data_clean), 0.8 * nrow(data_clean))
train <- data_clean[train_indices, ]
test <- data_clean[-train_indices, ]

# Remove customerID, TotalCharges, and Gender columns from train and test datasets
train <- train[, !names(train) %in% c("customerID", "TotalCharges", "gender")]
test <- test[, !names(test) %in% c("customerID", "TotalCharges", "gender")]

# Convert categorical variables to factors
categorical_vars <- c("Churn", "Contract", "PaymentMethod", "OnlineSecurity", "TechSupport", "InternetService", "OnlineBackup")
train[categorical_vars] <- lapply(train[categorical_vars], factor)
test[categorical_vars] <- lapply(test[categorical_vars], factor)

# Random Forest model
model <- randomForest(Churn ~ ., data = train)

# Make predictions on the train dataset
pred_train <- predict(model, newdata = train, type = "response")

# Evaluate model performance on train dataset
train_accuracy <- mean(pred_train == train$Churn)
train_error <- 1 - train_accuracy

# Make predictions on the test dataset
pred_test <- predict(model, newdata = test, type = "response")

# Evaluate model performance on test dataset
test_accuracy <- mean(pred_test == test$Churn)
test_error <- 1 - test_accuracy

# Confusion matrix for test dataset
confusion_matrix <- table(test$Churn, pred_test)

# Calculate evaluation metrics
TP <- confusion_matrix[2, 2]
TN <- confusion_matrix[1, 1]
FP <- confusion_matrix[1, 2]
FN <- confusion_matrix[2, 1]

precision <- TP / (TP + FP)
recall <- TP / (TP + FN)
f1_score <- 2 * precision * recall / (precision + recall)

# Print model results
cat("Train Accuracy:", train_accuracy, "\n")
cat("Train Error:", train_error, "\n")
cat("Test Accuracy:", test_accuracy, "\n")
cat("Test Error:", test_error, "\n")
cat("Precision:", precision, "\n")
cat("Recall:", recall, "\n")
cat("F1 Score:", f1_score, "\n")

# Plot the random forest model
plot(model)

```

```{r}
# Plotting variable importance
var_importance <- importance(model)
var_importance_df <- data.frame(Feature = row.names(var_importance), Importance = var_importance[, "MeanDecreaseGini"])

# Sort the feature importance in descending order
var_importance_df <- var_importance_df[order(-var_importance_df$Importance), ]

# Plotting the variable importance
ggplot(var_importance_df, aes(x = reorder(Feature, Importance), y = Importance)) +
  geom_bar(stat = "identity", fill = "blue") +
  labs(x = "Feature", y = "Importance") +
  ggtitle("Variable Importance") +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1))

# Print the important features
print(var_importance_df)
```

